# Generated by Django 3.2.7 on 2021-10-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlramSeries',
            fields=[
                ('alram_series_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alram_series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('anime_name', models.CharField(max_length=300)),
                ('anime_english_name', models.CharField(blank=True, max_length=300, null=True)),
                ('anime_japanese_name', models.CharField(blank=True, max_length=300, null=True)),
                ('anime_korean_name', models.CharField(blank=True, max_length=300, null=True)),
                ('anime_type', models.CharField(blank=True, max_length=7, null=True)),
                ('anime_episodes', models.IntegerField(blank=True, null=True)),
                ('anime_aired_start', models.DateField(blank=True, null=True)),
                ('anime_aired_end', models.DateField(blank=True, null=True)),
                ('anime_season', models.CharField(blank=True, max_length=20, null=True)),
                ('anime_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('anime_status', models.CharField(blank=True, max_length=8, null=True)),
                ('anime_rate', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'anime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimeChara',
            fields=[
                ('anime_chara_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'anime_chara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimeGenre',
            fields=[
                ('anime_genre_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'anime_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Animescore',
            fields=[
                ('animescore_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('animescore_score', models.FloatField()),
            ],
            options={
                'db_table': 'animescore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimeSeries',
            fields=[
                ('anime_series_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('anime_series_name', models.CharField(blank=True, max_length=300, null=True)),
                ('series_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anime_series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chara',
            fields=[
                ('chara_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chara_last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('chara_first_name', models.CharField(max_length=20)),
                ('chara_role', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'chara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteAnime',
            fields=[
                ('favorite_anime_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favorite_anime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteChara',
            fields=[
                ('favorite_chara_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('favoirte_character_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'favorite_chara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteSeiyu',
            fields=[
                ('favorite_seiyu_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favorite_seiyu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatingRatingcompleted',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('anime_id', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'rating_ratingcompleted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatingRecommendataioncf',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('anime_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rating_recommendataioncf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatingSimilaranimes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anime_id', models.IntegerField()),
                ('similar_anime_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rating_similaranimes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seiyu',
            fields=[
                ('seiyu_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('seiyu_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'seiyu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('series_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('user_status', models.CharField(blank=True, max_length=7, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=6, null=True)),
                ('user_birthday', models.DateField(blank=True, null=True)),
                ('user_nickname', models.CharField(max_length=15)),
                ('user_avatar', models.CharField(blank=True, max_length=200, null=True)),
                ('user_created_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatingCompleted',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='user_id')),
                ('anime_id', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommendataionCF',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('anime_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimilarAnimes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anime_id', models.IntegerField()),
                ('similar_anime_id', models.IntegerField()),
            ],
        ),
    ]
