# Generated by Django 3.2.7 on 2021-09-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCompleted',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='user_id')),
                ('anime_id', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommendataionCF',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('anime_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimilarAnimes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anime_id', models.IntegerField()),
                ('similar_anime_id', models.IntegerField()),
            ],
        ),
    ]
