# Generated by Django 3.2.7 on 2021-10-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('anime_id', models.IntegerField()),
                ('predicted_score', models.FloatField()),
                ('adusted_predicted_score', models.FloatField()),
            ],
        ),
    ]
