# Generated by Django 3.2.7 on 2021-10-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_predictedrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_favorite_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
            ],
        ),
    ]
