# Generated by Django 3.2.7 on 2021-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_user_favorite_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_favorite_genre',
            name='genre_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
